export * from './contracts.js';
import type {TypeMap,TypeName,OperationMap,ProjectionMap,ContractHandshake,LocalRequestFacts,CurrentBuildSubmission,ValidateBuildProposalRequest,ValidateBuildProposalResponse,BuildProposalProviderFacts,ScopedPreparedTransaction,ScopedPreparedTransactionResult,RegionInspection,MaterialMap,Catalogue,BuildProjection,FinalEffects,TargetFacts,SafetyProfile,Coverage} from './contracts.js';
export declare const version: '0.4.0';
export declare const wireVersions: ReadonlyArray<keyof OperationMap>;
export declare const compiledOperationsVersion: 'operations/v3';
export declare const contractHandshake: ContractHandshake;
export declare const schemaBundle: {readonly definitions: Readonly<Record<TypeName,unknown>>};
export declare const operationContracts: Readonly<Record<keyof OperationMap, ReadonlyArray<{operation:string;request:TypeName;response:TypeName}>>>;
export declare const ownership: Readonly<Record<string,{domainOwner:string;mutationCaller:string}>>;
export declare function validateType<K extends TypeName>(name:K,input:unknown):TypeMap[K];
export declare function admitType<K extends TypeName>(name:K,input:string|Uint8Array):TypeMap[K];
export declare function validateRequest<W extends keyof OperationMap,N extends keyof OperationMap[W]>(wire:W,name:N,input:unknown):OperationMap[W][N] extends {request:infer R}?R:never;
export declare const validateBoundRequest: typeof validateRequest;
export declare const admitRequest: typeof validateRequest;
export declare function validateResponse<W extends keyof OperationMap,N extends keyof OperationMap[W]>(wire:W,name:N,input:unknown):OperationMap[W][N] extends {response:infer R}?R:never;
export declare function validateBoundResponse<W extends keyof OperationMap,N extends keyof OperationMap[W]>(wire:W,name:N,request:unknown,response:unknown):OperationMap[W][N] extends {response:infer R}?R:never;
export declare function validateCurrentRequest<W extends keyof OperationMap,N extends keyof OperationMap[W]>(wire:W,name:N,input:unknown,facts:LocalRequestFacts):{request:OperationMap[W][N] extends {request:infer R}?R:never;requestDigest:string;disposition:'EXECUTE'|'RETURN_STORED'};
export declare function requestDigest<W extends keyof OperationMap,N extends keyof OperationMap[W]>(wire:W,name:N,input:unknown):string;
export declare function canonicalJSON(input:unknown):string;
export declare function digestValue<K extends keyof ProjectionMap>(kind:K,input:ProjectionMap[K]):{sha256:string;projection:ProjectionMap[K];canonicalUtf8:string;preimageUtf8:string;preimageHex:string;kind:K};
export declare function validateDigestBinding<K extends keyof ProjectionMap>(kind:K,input:ProjectionMap[K],hash:string):ReturnType<typeof digestValue<K>>;
export declare function checkContractHandshake(input:unknown,required?:{wires:ReadonlyArray<string>;factProfiles:ReadonlyArray<string>}):{result:'HANDSHAKE_VERSION_MATCH';advertised:ContractHandshake};
export declare function checkBuildProposalHandshake(input:unknown):{result:'HANDSHAKE_OPERATION_MATCH';advertised:ContractHandshake};
export declare function validateCurrentBuildSubmission(input:unknown,facts:LocalRequestFacts):CurrentBuildSubmission;
export declare function validateBuildProposalRequest(input:unknown):ValidateBuildProposalRequest;
export declare function validateBuildProposalContext(input:unknown,facts:BuildProposalProviderFacts):ValidateBuildProposalRequest;
export declare function validateBuildProposalResponse(input:unknown,response:unknown):ValidateBuildProposalResponse;
export declare function validateRegionInspection(input:unknown):RegionInspection;
export declare function validateFactsCoverage(input:TargetFacts,coverage:Coverage):TargetFacts;
export declare function validateStaticMaterials(input:MaterialMap,catalogue:Catalogue):MaterialMap;
export declare function validateWitnessCoherence(input:{build:BuildProjection;finalEffects:FinalEffects;targetFacts:TargetFacts;safetyProfile:SafetyProfile;catalogue:Catalogue}):{coherent:true;authenticityVerified:false;worldWrites:0};
export declare function projectScopedPreparedTransaction(input:ScopedPreparedTransactionResult):ScopedPreparedTransaction;
export declare function validateExactEffects(operations:unknown,materials:unknown,effects:unknown):unknown;
export declare function decodeRawJSON(input:string|Uint8Array):unknown;
export declare class ContractError extends Error {readonly code:string;readonly phase:string;readonly reason:string;readonly mutationState:string;readonly publicError:Readonly<Record<string,unknown>>;}
export declare function validateWorldSelection(input:unknown,facts:LocalRequestFacts,connection:unknown):import('./contracts.js').SelectWorldConnectionRequest;
export declare function validateCommitReadback(receipt:unknown,expected:unknown,actual:unknown,durableHistory:unknown):import('./contracts.js').ReceiptProjection;
export declare const placementSettingDescriptors: ReadonlyArray<{readonly name:string;readonly owner:string;readonly type:string;readonly default:number;readonly scope:string;readonly editable:boolean;readonly meaning:string;readonly consequence:string;readonly whenUnsetOrInvalid:string}>;
export declare const placementInvariants: ReadonlyArray<{readonly id:string;readonly owner:string;readonly switchable:false;readonly text:string;readonly consequence:string}>;
export declare const settingsSurface: {readonly where:string;readonly rule:string;readonly currentEvidence:'NOT_RUN'};
