import * as C from 'hanaworlds-contracts';
import * as F from 'hanaworlds-contracts/fixture';
import {readFile,writeFile} from 'node:fs/promises';
import {harness,captureError,Blocked,json} from './harness.mjs';
const {check,finish}=harness(process.env.SUITE_LABEL || 'conformance');
const read=async name=>JSON.parse(await readFile(new URL('../fixtures/candidate/'+name+'.json',import.meta.url),'utf8'));
const goldens=(await read('production-goldens')).vectors, wires=(await read('wire-inputs')).requests, closures=(await read('closure-oracles')).cases, events=(await read('canvas-events')).cases, semantic=await read('semantic-cases');
const approvedProfile=JSON.parse(await readFile(new URL('../spec/CONTRACT_SCHEMA_PROFILE.json',import.meta.url),'utf8'));
const closure=JSON.parse(await readFile(new URL('../spec/CONTRACT_SEMANTIC_CLOSURE.json',import.meta.url),'utf8'));
const assets={requests:wires,goldens:goldens.map(({id,kind,payload})=>({id,kind,payload}))};
const utf8=s=>new TextEncoder().encode(s);const compatibility=C.runtimeCompatibility();
function compatible(){if(!compatibility.compatible)throw new Blocked('Actual Unicode runtime does not meet the frozen Unicode17 requirement; no substitute normalization was executed.',compatibility);}
for(const g of goldens) await check(g.id,'production-golden',({same})=>{const actual=C.digestValue(g.kind,g.payload);same(actual.projection,g.payload,'$.payload');for(const key of ['canonicalUtf8','preimageUtf8','preimageHex','sha256'])same(actual[key],g.expected[key],'$.'+key);same(C.digestRaw(g.kind,utf8(JSON.stringify(g.payload))).sha256,g.expected.sha256,'$.rawDigest');});
for(const q of wires) await check(q.id,'wire-request',({same})=>{same(C.validateRequest(q.wire,q.operation,q.request),q.request);same(C.admitRequest(q.wire,q.operation,utf8(JSON.stringify(q.request))),q.request);same(C.validateBoundRequest(q.wire,q.operation,q.request),q.request);});
for(const c of closures) await check(c.id,'closure',({expectedSubset})=>expectedSubset(F.evaluateClosureFixture(c.wire,c.dimension,c.input,assets),c.expected),{wire:c.wire,dimension:c.dimension,kind:c.kind,rowId:c.id.replace(/-(?:VALID|INVALID)$/,'')});
for(const c of events) await check(c.id,'canvas-event',({expectedSubset})=>expectedSubset(F.evaluateCanvasEventFixture(c.eventType,c.input),c.expected),{eventType:c.eventType,kind:c.kind});
for(const c of semantic.cases) await check(c.id,'semantic',({expectedSubset})=>{if(['DIGEST-NONNORMALIZED','NAME-CONCURRENT-CAS'].includes(c.id))compatible();expectedSubset(F.evaluateSemanticFixture(c.input),c.expected);},{kind:c.kind});
for(const c of semantic.nameCases) await check(c.id,'name',({same,expectedSubset})=>{const a=c.a??c.repeat.repeat(c.count);if(c.valid===false){expectedSubset(captureError(()=>C.normalizeName(a)),{code:'INVALID_NAME',phase:'validate',mutationState:'NONE',reason:c.reason});return;}compatible();const x=C.normalizeName(a);same(x.displayName,C.validateNameSyntax(a));if(c.b!==undefined)same(x.comparisonKey===C.normalizeName(c.b).comparisonKey,c.equal);else same(x.displayName.length>0,true);});
await check('COMPAT-no-silent-normalization','compatibility',({same,expectedSubset})=>{same(compatibility.unicode,process.versions.unicode);same(compatibility.icu,process.versions.icu);if(!compatibility.compatible)expectedSubset(captureError(()=>C.normalizeName('fixture')), {code:'CAPABILITY_UNAVAILABLE',phase:'validate',reason:'POLICY_UNAVAILABLE',mutationState:'NONE'});else same(C.normalizeName(' A ').comparisonKey,'a');});
await check('INVENTORY-all-frozen-coverage','inventory',({same})=>{same(C.schemaInventory.length,243);same(C.wireVersions,approvedProfile.wireVersions);same(Object.keys(C.digestProfile.projectionTypes).length,19);same(closures.length,140);same(closure.rows.length,70);for(const row of closure.rows){const a=closures.filter(x=>x.id.startsWith(row.id+'-'));same(a.filter(x=>x.kind==='valid').length,1,row.id+'.valid');same(a.filter(x=>x.kind!=='valid').length,1,row.id+'.negative');}same(events.length,30);same(events.filter(x=>x.kind==='valid').length,16);same(events.filter(x=>x.kind==='invalid').length,14);same(Object.keys(C.canvasEventRules).length,14);same(C.operationContracts['canvas/v2'].length,16);same(Object.values(C.operationContracts).reduce((n,a)=>n+a.length,0),38);});
for(const c of events.filter(x=>x.kind==='valid')) await check(c.id+'-NO-CHANGE','event-trigger',({same})=>same(F.eventTransitionEligible(c.eventType,c.input,{evidence:'FIXTURE'}),false));
for(const c of events.filter(x=>x.kind==='valid'&&['WorldConnectionInventoryChanged','ObjectInventoryChanged','HistoryInventoryChanged'].includes(x.eventType))) await check(c.id+'-OBSERVED-CHANGE','event-trigger',({same})=>same(F.eventTransitionEligible(c.eventType,c.input,{evidence:'FIXTURE',actualDurableChange:true}),true));
await check('NUMERIC-JCS-minus-zero-equivalence','strict-digest',({same})=>{same(C.canonicalJSON({b:1.0,a:-0}),'{"a":0,"b":1}');same(C.canonicalJSON({a:-0}),C.canonicalJSON({a:0}));same(C.canonicalJSON(['B','A'])===C.canonicalJSON(['A','B']),false);same(C.canonicalJSON({x:'ガ'})===C.canonicalJSON({x:'カ\u3099'}),false);});
await check('PROJECTION-no-recursive-metadata-delete','strict-digest',({same})=>{const g=goldens.find(x=>x.kind==='before-image');const p=json(g.payload);p.records[0].metadata['digest']='MUST_STAY';const result=C.digestValue('before-image',p);same(result.canonicalUtf8.includes('MUST_STAY'),true);same(result.sha256===g.expected.sha256,false);});
await check('UNKNOWN-top-level-projection-metadata','strict-digest',({expectedSubset})=>{const g=goldens[0];expectedSubset(captureError(()=>C.digestValue(g.kind,{...g.payload,metadata:{}})),{code:'UNKNOWN_REQUIRED_FIELD',phase:'decode',reason:'UNKNOWN_FIELD',mutationState:'NONE'});});
await check('REFERENCE-exact-no-normalization','refs',({same})=>{for(const v of [' A ','a','ガ','カ\u3099'])same(C.validateType('Ref',v),v);});
await check('SET-duplicate-before-sorting','arrays',({expectedSubset})=>expectedSubset(captureError(()=>C.validateType('Positions',[[0,0,0],[0,0,0]])),{code:'SCHEMA_INVALID',phase:'validate',reason:'INVALID_SHAPE',mutationState:'NONE'}));
await check('SET-unsorted-no-mutation','arrays',({same,expectedSubset})=>{const v=[[2,0,0],[1,0,0]],prior=json(v);expectedSubset(captureError(()=>C.validateType('Positions',v)),{code:'SCHEMA_INVALID',phase:'validate',reason:'INVALID_SHAPE'});same(v,prior);});
await check('SAFETY-reject-bare-proof','typed-proof',({expectedSubset})=>expectedSubset(captureError(()=>C.validateType('Witness',{safe:true})),{code:'SCHEMA_INVALID',phase:'decode',reason:'INVALID_SHAPE',mutationState:'NONE'}));
await check('PUBLIC-error-does-not-leak-exception','privacy',({same})=>{const e=C.publicError(new Error('FIXTURE-secret/private/path'));same(Object.keys(e).sort(),['causeCode','code','mutationState','phase','reason','retryability','transactionRef'].sort());same(JSON.stringify(e).includes('FIXTURE-secret'),false);C.validateType('Error',e);});
await check('JCS-inherited-hook-not-called','pure-json',({same,expectedSubset})=>{let calls=0;Object.defineProperty(Object.prototype,'toJSON',{configurable:true,value(){calls++;return 'bad';}});let actual;try{actual=captureError(()=>C.canonicalJSON({a:1}));}finally{delete Object.prototype.toJSON;}expectedSubset(actual,{code:'SCHEMA_INVALID',phase:'decode',reason:'INVALID_SHAPE'});same(calls,0);});
// Build structural representatives exclusively from admitted fixture payloads, not expected objects.
const examples=new Map();const definitions=C.schemaBundle.definitions;
function collect(name,value){if(name.includes('|')){if(value!==null)collect(name.split('|').find(x=>x!=='null'),value);return;}if(name.startsWith('=')||name==='null')return;if(!examples.has(name))examples.set(name,json(value));const t=approvedProfile.types[name];if(!t||value===null)return;
 if(t.type==='object')for(const[k,n]of Object.entries(t.fields))collect(n,value[k]);
 else if(t.type==='discriminated-object')for(const[k,n]of Object.entries({...t.common,...t.variants[value[t.discriminator]]}))collect(n,value[k]);
 else if(t.type==='array')for(const v of value)collect(t.items,v);
 else if(t.type==='tuple')value.forEach((v,i)=>collect(t.items[i],v));
 else if(t.type==='map')for(const[k,v]of Object.entries(value)){collect(t.keyType,k);collect(t.values,v);}
}
for(const g of goldens)collect(approvedProfile.digest.projectionTypes[g.kind],g.payload);for(const q of wires)collect(q.requestType,q.request);for(const e of events.filter(x=>x.kind==='valid'))collect(e.eventType,e.input);
function make(name,trail=[]){if(name.includes('|'))return null;if(name==='null')return null;if(name.startsWith('=')){const s=name.slice(1);return /^(?:true|false|null|\d+)$/.test(s)?JSON.parse(s):s;}if(examples.has(name))return json(examples.get(name));if(trail.includes(name))throw new Error('Recursive nonnullable schema '+name);const t=approvedProfile.types[name],next=[...trail,name];let value;
 if(t.type==='object'){value=Object.fromEntries(Object.entries(t.fields).map(([k,n])=>[k,make(n,next)]));if(Object.hasOwn(t.fields,'result')&&Object.hasOwn(t.fields,'error')){value.result=null;value.error=make('Error',next);}}
 else if(t.type==='discriminated-object'){const key=Object.keys(t.variants)[0];value=Object.fromEntries(Object.entries({...t.common,...t.variants[key],[t.discriminator]:'='+key}).map(([k,n])=>[k,make(n,next)]));}
 else if(t.type==='enum')value=t.values[0];else if(t.type==='array')value=Array.from({length:t.minItems??0},()=>make(t.items,next));else if(t.type==='tuple')value=t.items.map(x=>make(x,next));else if(t.type==='map')value=t.minEntries?{fixture:make(t.values,next)}:{};else if(t.type==='string')value=name==='Digest'?'0'.repeat(64):'fixture';else if(t.type==='boolean')value=false;else value=t.exclusiveMinimum!==undefined?t.exclusiveMinimum+1:Math.max(0,t.minimum??0);
 if(name==='SavedResourceReceipt')value.durable=true;
 examples.set(name,value);return json(value);
}
const sampleInventory=[];
for(const name of C.schemaInventory)await check('TYPE-'+name,'type-inventory',({same})=>{const value=make(name);same(C.validateType(name,value),value);sampleInventory.push({name,value});});
for(const[wire,ops]of Object.entries(C.operationContracts)){const binding=await import('hanaworlds-contracts/'+wire);for(const op of ops)await check('OP-'+wire+'/'+op.operation,'operation-binding',({same,expectedSubset})=>{const req=make(op.request),res=make(op.response);same(binding.validate(op.operation,req),req);same(binding.admit(op.operation,utf8(JSON.stringify(req))),req);same(binding.response(op.operation,res),res);expectedSubset(captureError(()=>binding.validate(op.operation,{...req,unapprovedExtension:true})),{code:'UNKNOWN_REQUIRED_FIELD',phase:'decode',reason:'UNKNOWN_FIELD',mutationState:'NONE'});if(op.alternateResult){const alt=make(op.alternateResult);same(binding.response(op.operation,alt),alt);}});}
await writeFile('evidence/schema-samples.json',JSON.stringify({evidence:'FIXTURE',samples:sampleInventory},null,2)+'\n');
const report=await finish();
const rowCoverage=closure.rows.map(row=>({id:row.id,protocol:row.protocol,dimension:row.dimension,rule:row.rule,authorityRefs:row.authorityRefs,cases:report.results.filter(x=>x.rowId===row.id).map(x=>({id:x.id,kind:x.kind,status:x.status,expectedFields:x.comparisons.map(c=>c.path)}))}));
await writeFile('evidence/closure-coverage.json',JSON.stringify({evidence:'FIXTURE',rowCount:rowCoverage.length,rows:rowCoverage},null,2)+'\n');
