import type * as T from './contracts.js';
export * from './contracts.js';
export type JSONValue = null | boolean | number | string | ReadonlyArray<JSONValue> | { readonly [key: string]: JSONValue };
export interface DigestResult<P> { readonly kind: T.DigestKind; readonly projection: P; readonly canonicalUtf8: string; readonly preimageUtf8: string; readonly preimageHex: string; readonly sha256: T.Digest; }
export interface OperationContract { readonly operation: string; readonly request: T.TypeName; readonly response: T.TypeName; readonly alternateResult?: T.TypeName; readonly event?: string; readonly validationOrder: ReadonlyArray<string>; readonly failureCodes: ReadonlyArray<T.ErrorCode>; readonly successSemantics: string; readonly idempotency: string; readonly scope?: string; readonly requestName?: string; readonly responseName?: string; readonly baselineOperation?: string; }
export declare class ContractError extends Error { constructor(code: T.ErrorCode, phase: T.Phase, reason: T.ErrorReason, details?: Partial<T.Error>); readonly publicError: T.Error; readonly code: T.ErrorCode; readonly phase: T.Phase; readonly reason: T.ErrorReason; readonly mutationState: T.MutationState; readonly retryability: T.Retryability; }
export declare function publicError(error: unknown): T.Error;
export declare const version: '0.3.0';
export declare const wireVersions: ReadonlyArray<T.WireVersion>;
export declare const compiledOperationsVersion: 'operations/v2';
export declare const operationContracts: { readonly [W in T.WireVersion]: ReadonlyArray<OperationContract> };
export declare const canvasEventRules: Readonly<Record<'WorldConnectionInventoryChanged' | 'WorldConnectionSelectionChanged' | 'ActiveWorldChanged' | 'ObjectInventoryChanged' | 'ObjectCreated' | 'ObjectNameChanged' | 'ActiveObjectSelectionReplaced' | 'ObjectInspectionInvalidated' | 'AffectedObjectAnalysisReady' | 'AffectedObjectNotificationRequired' | 'TransactionAppliedPendingReadback' | 'TransactionVerified' | 'HistoryPositionChanged' | 'HistoryInventoryChanged', JSONValue>>;
export declare const errorPrecedence: JSONValue;
export declare const ownership: Readonly<Record<T.WireVersion, { readonly domainOwner: string; readonly mutationCaller: string | null }>>;
export declare const digestProfile: JSONValue;
export declare const schemaInventory: ReadonlyArray<T.TypeName>;
export declare const schemaBundle: { readonly $schema: string; readonly $id: string; readonly definitions: Readonly<Record<T.TypeName, JSONValue>> };
export declare const providerGates: JSONValue;
export declare function decodeRawJSON(bytes: Uint8Array): JSONValue;
export declare function snapshotJSON(value: unknown): JSONValue;
export declare function assertPureJSON(value: unknown): void;
export declare function deepFreeze<V>(value: V): Readonly<V>;
export declare function validateType<N extends T.TypeName>(typeName: N, value: unknown): T.TypeMap[N];
export declare function assertType<N extends T.TypeName>(typeName: N, value: unknown): asserts value is T.TypeMap[N];
export declare function admitType<N extends T.TypeName>(typeName: N, bytes: Uint8Array): T.TypeMap[N];
export declare function validateCanvasEvent<N extends keyof typeof canvasEventRules>(typeName: N, value: unknown): T.TypeMap[N];
export declare function validateRequest<W extends T.WireVersion, O extends keyof T.OperationMap[W]>(wire: W, operation: O, value: unknown): T.OperationMap[W][O] extends { readonly request: infer Q } ? Q : never;
export declare function admitRequest<W extends T.WireVersion, O extends keyof T.OperationMap[W]>(wire: W, operation: O, bytes: Uint8Array): T.OperationMap[W][O] extends { readonly request: infer Q } ? Q : never;
export declare function validateResponse<W extends T.WireVersion, O extends keyof T.OperationMap[W]>(wire: W, operation: O, value: unknown): T.OperationMap[W][O] extends { readonly response: infer Q } ? Q : never;
export declare const validateBoundRequest: typeof validateRequest;
export declare function canonicalJSON(value: unknown): string;
export declare function project<K extends T.DigestKind>(kind: K, payload: unknown): T.ProjectionMap[K];
export declare function digestValue<K extends T.DigestKind>(kind: K, payload: unknown): DigestResult<T.ProjectionMap[K]>;
export declare function digestRaw<K extends T.DigestKind>(kind: K, bytes: Uint8Array): DigestResult<T.ProjectionMap[K]>;
export declare function projectField<K extends T.DigestKind, N extends T.TypeName>(kind: K, sourceType: N, source: unknown, field: keyof T.TypeMap[N]): T.ProjectionMap[K];
export declare function validateDigestBinding<K extends T.DigestKind>(kind: K, payload: unknown, providedDigest: T.Digest): DigestResult<T.ProjectionMap[K]>;
export interface RuntimeCompatibility { readonly compatible: boolean; readonly node: string; readonly icu: string; readonly unicode: string; readonly requiredUnicode: '17.0'; readonly persistentNameKeysAllowed: boolean; readonly [key: string]: JSONValue; }
export declare function runtimeCompatibility(): RuntimeCompatibility;
export declare function requireUnicode17(): RuntimeCompatibility;
export declare function validateNameSyntax(value: unknown): string;
export declare function normalizeName(value: unknown): { readonly displayName: string; readonly comparisonKey: string };
export declare function compareUTF16(a: string, b: string): number;
export declare function comparePosition(a: T.Position, b: T.Position): number;
export declare function boxCellCount(box: T.Box): bigint;
export declare function unionCellCount(boxes: ReadonlyArray<T.Box>): bigint;
export declare function validateExactEffects(operations: T.BuildOps, materials: T.MaterialMap, effects: T.Effects): void;
export declare function validateFactsCoverage(facts: unknown, coverage: unknown): T.TargetFacts;
export declare function validateStaticMaterials(materials: unknown, catalogue: unknown): T.MaterialMap;
export declare function validateWitnessCoherence(input: { readonly build: unknown; readonly finalEffects: unknown; readonly targetFacts: unknown; readonly safetyProfile: unknown; readonly catalogue: unknown; readonly witnesses: unknown }): { readonly coherent: true; readonly authenticityVerified: false; readonly providerAuthorization: 'NOT_RUN'; readonly worldWrites: 0 };
export * as interactionSurfaceV2 from '../bindings/interaction-surface-v2.js';
export * as worldAdapterV2 from '../bindings/world-adapter-v2.js';
export * as canvasV2 from '../bindings/canvas-v2.js';
export * as sessionV2 from '../bindings/session-v2.js';
export * as painterV2 from '../bindings/painter-v2.js';
export * as referenceBriefV2 from '../bindings/ReferenceBrief-v2.js';
export * as buildV2 from '../bindings/BUILD-V2.js';
export * as operationsV2 from '../bindings/operations-v2.js';
