import type * as T from '../types/contracts.js';
export declare const contractVersion: "session/v2";
export declare const operations: ReadonlyArray<import('../types/index.js').OperationContract>;
export declare function validate(operation: "StartOrResumeSession", value: unknown): T.StartOrResumeSessionRequest;
export declare function admit(operation: "StartOrResumeSession", bytes: Uint8Array): T.StartOrResumeSessionRequest;
export declare function response(operation: "StartOrResumeSession", value: unknown): T.StartOrResumeSessionResponse;
export declare function validate(operation: "AppendMultimodalTurn", value: unknown): T.AppendMultimodalTurnRequest;
export declare function admit(operation: "AppendMultimodalTurn", bytes: Uint8Array): T.AppendMultimodalTurnRequest;
export declare function response(operation: "AppendMultimodalTurn", value: unknown): T.AppendMultimodalTurnResponse;
export declare function validate(operation: "AnswerClarification", value: unknown): T.AnswerClarificationRequest;
export declare function admit(operation: "AnswerClarification", bytes: Uint8Array): T.AnswerClarificationRequest;
export declare function response(operation: "AnswerClarification", value: unknown): T.AnswerClarificationResponse;
export declare function validate(operation: "SwitchWorldContext", value: unknown): T.SwitchWorldContextRequest;
export declare function admit(operation: "SwitchWorldContext", bytes: Uint8Array): T.SwitchWorldContextRequest;
export declare function response(operation: "SwitchWorldContext", value: unknown): T.SwitchWorldContextResponse;
export declare function validate(operation: "RecordActionReceipt", value: unknown): T.RecordActionReceiptRequest;
export declare function admit(operation: "RecordActionReceipt", bytes: Uint8Array): T.RecordActionReceiptRequest;
export declare function response(operation: "RecordActionReceipt", value: unknown): T.RecordActionReceiptResponse;
export declare function validate(operation: "DeleteSession", value: unknown): T.DeleteSessionRequest;
export declare function admit(operation: "DeleteSession", bytes: Uint8Array): T.DeleteSessionRequest;
export declare function response(operation: "DeleteSession", value: unknown): T.DeleteSessionResponse;
export declare function validate(operation: "PersistRequiredArtifactResources", value: unknown): T.PersistRequiredArtifactResourcesRequest;
export declare function admit(operation: "PersistRequiredArtifactResources", bytes: Uint8Array): T.PersistRequiredArtifactResourcesRequest;
export declare function response(operation: "PersistRequiredArtifactResources", value: unknown): T.PersistRequiredArtifactResourcesResponse;
export declare function validate(operation: "ReopenExistingArtifact", value: unknown): T.ReopenExistingArtifactRequest;
export declare function admit(operation: "ReopenExistingArtifact", bytes: Uint8Array): T.ReopenExistingArtifactRequest;
export declare function response(operation: "ReopenExistingArtifact", value: unknown): T.ReopenExistingArtifactResponse;
