import type * as T from '../types/contracts.js';
export declare const contractVersion: "world-adapter/v2";
export declare const operations: ReadonlyArray<import('../types/index.js').OperationContract>;
export declare function validate(operation: "DiscoverConnections", value: unknown): T.DiscoverConnectionsRequest;
export declare function admit(operation: "DiscoverConnections", bytes: Uint8Array): T.DiscoverConnectionsRequest;
export declare function response(operation: "DiscoverConnections", value: unknown): T.DiscoverConnectionsResponse;
export declare function validate(operation: "ListWorlds", value: unknown): T.ListWorldsRequest;
export declare function admit(operation: "ListWorlds", bytes: Uint8Array): T.ListWorldsRequest;
export declare function response(operation: "ListWorlds", value: unknown): T.ListWorldsResponse;
export declare function validate(operation: "AuthorizeBinding", value: unknown): T.AuthorizeBindingRequest;
export declare function admit(operation: "AuthorizeBinding", bytes: Uint8Array): T.AuthorizeBindingRequest;
export declare function response(operation: "AuthorizeBinding", value: unknown): T.AuthorizeBindingResponse;
export declare function validate(operation: "InspectWorld", value: unknown): T.InspectWorldRequest;
export declare function admit(operation: "InspectWorld", bytes: Uint8Array): T.InspectWorldRequest;
export declare function response(operation: "InspectWorld", value: unknown): T.InspectWorldResponse;
export declare function validate(operation: "PrepareRecoverableTransaction", value: unknown): T.PrepareRecoverableTransactionRequest;
export declare function admit(operation: "PrepareRecoverableTransaction", bytes: Uint8Array): T.PrepareRecoverableTransactionRequest;
export declare function response(operation: "PrepareRecoverableTransaction", value: unknown): T.PrepareRecoverableTransactionResponse;
export declare function validate(operation: "ApplyCompiledTransaction", value: unknown): T.ApplyCompiledTransactionRequest;
export declare function admit(operation: "ApplyCompiledTransaction", bytes: Uint8Array): T.ApplyCompiledTransactionRequest;
export declare function response(operation: "ApplyCompiledTransaction", value: unknown): T.ApplyCompiledTransactionResponse;
export declare function validate(operation: "Readback", value: unknown): T.ReadbackRequest;
export declare function admit(operation: "Readback", bytes: Uint8Array): T.ReadbackRequest;
export declare function response(operation: "Readback", value: unknown): T.ReadbackResponse;
export declare function validate(operation: "QueryTransaction", value: unknown): T.QueryTransactionRequest;
export declare function admit(operation: "QueryTransaction", bytes: Uint8Array): T.QueryTransactionRequest;
export declare function response(operation: "QueryTransaction", value: unknown): T.QueryTransactionResponse;
export declare function validate(operation: "RestoreTransaction", value: unknown): T.RestoreTransactionRequest;
export declare function admit(operation: "RestoreTransaction", bytes: Uint8Array): T.RestoreTransactionRequest;
export declare function response(operation: "RestoreTransaction", value: unknown): T.RestoreTransactionResponse;
